// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConstraint(arg1, arg2) {
  return window['go']['launcher']['App']['AddConstraint'](arg1, arg2);
}

export function AddLoadFirst(arg1) {
  return window['go']['launcher']['App']['AddLoadFirst'](arg1);
}

export function AddLoadLast(arg1) {
  return window['go']['launcher']['App']['AddLoadLast'](arg1);
}

export function Autosort() {
  return window['go']['launcher']['App']['Autosort']();
}

export function CreateLauncherCategory(arg1) {
  return window['go']['launcher']['App']['CreateLauncherCategory'](arg1);
}

export function DeleteLauncherCategory(arg1) {
  return window['go']['launcher']['App']['DeleteLauncherCategory'](arg1);
}

export function DisableMod(arg1) {
  return window['go']['launcher']['App']['DisableMod'](arg1);
}

export function EnableMod(arg1) {
  return window['go']['launcher']['App']['EnableMod'](arg1);
}

export function FetchWorkshopMetadataForMod(arg1) {
  return window['go']['launcher']['App']['FetchWorkshopMetadataForMod'](arg1);
}

export function GetAllMods() {
  return window['go']['launcher']['App']['GetAllMods']();
}

export function GetAutoDetectedGameExe() {
  return window['go']['launcher']['App']['GetAutoDetectedGameExe']();
}

export function GetAutoDetectedModsDir() {
  return window['go']['launcher']['App']['GetAutoDetectedModsDir']();
}

export function GetConfigPath() {
  return window['go']['launcher']['App']['GetConfigPath']();
}

export function GetConstraints() {
  return window['go']['launcher']['App']['GetConstraints']();
}

export function GetGameActivePlaysetIndex() {
  return window['go']['launcher']['App']['GetGameActivePlaysetIndex']();
}

export function GetGameExe() {
  return window['go']['launcher']['App']['GetGameExe']();
}

export function GetLauncherActivePlaysetIndex() {
  return window['go']['launcher']['App']['GetLauncherActivePlaysetIndex']();
}

export function GetLauncherLayout() {
  return window['go']['launcher']['App']['GetLauncherLayout']();
}

export function GetLoadOrder() {
  return window['go']['launcher']['App']['GetLoadOrder']();
}

export function GetModsDir() {
  return window['go']['launcher']['App']['GetModsDir']();
}

export function GetModsDirStatus() {
  return window['go']['launcher']['App']['GetModsDirStatus']();
}

export function GetPlaysetNames() {
  return window['go']['launcher']['App']['GetPlaysetNames']();
}

export function Greet(arg1) {
  return window['go']['launcher']['App']['Greet'](arg1);
}

export function IsUnsubscribeEnabled() {
  return window['go']['launcher']['App']['IsUnsubscribeEnabled']();
}

export function LaunchGame() {
  return window['go']['launcher']['App']['LaunchGame']();
}

export function ListSupportedGames() {
  return window['go']['launcher']['App']['ListSupportedGames']();
}

export function OpenConfigFolder() {
  return window['go']['launcher']['App']['OpenConfigFolder']();
}

export function OpenExternalLink(arg1) {
  return window['go']['launcher']['App']['OpenExternalLink'](arg1);
}

export function OpenWorkshopItem(arg1) {
  return window['go']['launcher']['App']['OpenWorkshopItem'](arg1);
}

export function PickExecutable() {
  return window['go']['launcher']['App']['PickExecutable']();
}

export function PickFolder() {
  return window['go']['launcher']['App']['PickFolder']();
}

export function RefreshGamePaths() {
  return window['go']['launcher']['App']['RefreshGamePaths']();
}

export function RemoveConstraint(arg1, arg2) {
  return window['go']['launcher']['App']['RemoveConstraint'](arg1, arg2);
}

export function RemoveLoadFirst(arg1) {
  return window['go']['launcher']['App']['RemoveLoadFirst'](arg1);
}

export function RemoveLoadLast(arg1) {
  return window['go']['launcher']['App']['RemoveLoadLast'](arg1);
}

export function ResetGameExeToAuto() {
  return window['go']['launcher']['App']['ResetGameExeToAuto']();
}

export function ResetModsDirToAuto() {
  return window['go']['launcher']['App']['ResetModsDirToAuto']();
}

export function SaveCompiledLoadOrder() {
  return window['go']['launcher']['App']['SaveCompiledLoadOrder']();
}

export function SetActiveGame(arg1) {
  return window['go']['launcher']['App']['SetActiveGame'](arg1);
}

export function SetGameExe(arg1) {
  return window['go']['launcher']['App']['SetGameExe'](arg1);
}

export function SetGamePaths(arg1, arg2, arg3) {
  return window['go']['launcher']['App']['SetGamePaths'](arg1, arg2, arg3);
}

export function SetLauncherActivePlaysetIndex(arg1) {
  return window['go']['launcher']['App']['SetLauncherActivePlaysetIndex'](arg1);
}

export function SetLauncherLayout(arg1) {
  return window['go']['launcher']['App']['SetLauncherLayout'](arg1);
}

export function SetLoadOrder(arg1) {
  return window['go']['launcher']['App']['SetLoadOrder'](arg1);
}

export function SetModsDir(arg1) {
  return window['go']['launcher']['App']['SetModsDir'](arg1);
}

export function UnsubscribeWorkshopMod(arg1) {
  return window['go']['launcher']['App']['UnsubscribeWorkshopMod'](arg1);
}
