// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {launcher} from '../models';
import {steam} from '../models';
import {mods} from '../models';
import {domain} from '../models';
import {game} from '../models';

export function AddConstraint(arg1:string,arg2:string):Promise<void>;

export function AddLoadFirst(arg1:string):Promise<void>;

export function AddLoadLast(arg1:string):Promise<void>;

export function Autosort():Promise<Array<string>>;

export function CreateLauncherCategory(arg1:string):Promise<launcher.LauncherLayout>;

export function DeleteLauncherCategory(arg1:string):Promise<launcher.LauncherLayout>;

export function DisableMod(arg1:string):Promise<void>;

export function EnableMod(arg1:string):Promise<void>;

export function FetchWorkshopMetadataForMod(arg1:string):Promise<steam.WorkshopItem>;

export function GetAllMods():Promise<Array<mods.Mod>>;

export function GetAutoDetectedGameExe():Promise<string>;

export function GetAutoDetectedModsDir():Promise<string>;

export function GetConfigPath():Promise<string>;

export function GetConstraints():Promise<Array<domain.Constraint>>;

export function GetGameActivePlaysetIndex():Promise<number>;

export function GetGameExe():Promise<string>;

export function GetLauncherActivePlaysetIndex():Promise<number>;

export function GetLauncherLayout():Promise<launcher.LauncherLayout>;

export function GetLoadOrder():Promise<Array<string>>;

export function GetModsDir():Promise<string>;

export function GetModsDirStatus():Promise<launcher.ModsDirStatus>;

export function GetPlaysetNames():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function IsUnsubscribeEnabled():Promise<boolean>;

export function LaunchGame():Promise<void>;

export function ListSupportedGames():Promise<Array<game.DetectedGame>>;

export function OpenConfigFolder():Promise<void>;

export function OpenExternalLink(arg1:string):Promise<void>;

export function OpenWorkshopItem(arg1:string):Promise<void>;

export function PickExecutable():Promise<string>;

export function PickFolder():Promise<string>;

export function RefreshGamePaths():Promise<void>;

export function RemoveConstraint(arg1:string,arg2:string):Promise<void>;

export function RemoveLoadFirst(arg1:string):Promise<void>;

export function RemoveLoadLast(arg1:string):Promise<void>;

export function ResetGameExeToAuto():Promise<string>;

export function ResetModsDirToAuto():Promise<string>;

export function SaveCompiledLoadOrder():Promise<Array<string>>;

export function SetActiveGame(arg1:string):Promise<void>;

export function SetGameExe(arg1:string):Promise<void>;

export function SetGamePaths(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetLauncherActivePlaysetIndex(arg1:number):Promise<void>;

export function SetLauncherLayout(arg1:launcher.LauncherLayout):Promise<void>;

export function SetLoadOrder(arg1:Array<string>):Promise<void>;

export function SetModsDir(arg1:string):Promise<void>;

export function UnsubscribeWorkshopMod(arg1:string):Promise<void>;
