// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConstraint(arg1, arg2) {
  return window['go']['main']['App']['AddConstraint'](arg1, arg2);
}

export function AddLoadFirst(arg1) {
  return window['go']['main']['App']['AddLoadFirst'](arg1);
}

export function AddLoadLast(arg1) {
  return window['go']['main']['App']['AddLoadLast'](arg1);
}

export function Autosort() {
  return window['go']['main']['App']['Autosort']();
}

export function CreateLauncherCategory(arg1) {
  return window['go']['main']['App']['CreateLauncherCategory'](arg1);
}

export function DeleteLauncherCategory(arg1) {
  return window['go']['main']['App']['DeleteLauncherCategory'](arg1);
}

export function DisableMod(arg1) {
  return window['go']['main']['App']['DisableMod'](arg1);
}

export function EnableMod(arg1) {
  return window['go']['main']['App']['EnableMod'](arg1);
}

export function FetchWorkshopMetadataBatch(arg1) {
  return window['go']['main']['App']['FetchWorkshopMetadataBatch'](arg1);
}

export function FetchWorkshopMetadataForMod(arg1) {
  return window['go']['main']['App']['FetchWorkshopMetadataForMod'](arg1);
}

export function GetActiveGameID() {
  return window['go']['main']['App']['GetActiveGameID']();
}

export function GetAllMods() {
  return window['go']['main']['App']['GetAllMods']();
}

export function GetAutoDetectedGameExe() {
  return window['go']['main']['App']['GetAutoDetectedGameExe']();
}

export function GetAutoDetectedModsDir() {
  return window['go']['main']['App']['GetAutoDetectedModsDir']();
}

export function GetAvailableGames() {
  return window['go']['main']['App']['GetAvailableGames']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetConstraints() {
  return window['go']['main']['App']['GetConstraints']();
}

export function GetGameActivePlaysetIndex() {
  return window['go']['main']['App']['GetGameActivePlaysetIndex']();
}

export function GetGameExe() {
  return window['go']['main']['App']['GetGameExe']();
}

export function GetLauncherActivePlaysetIndex() {
  return window['go']['main']['App']['GetLauncherActivePlaysetIndex']();
}

export function GetLauncherLayout() {
  return window['go']['main']['App']['GetLauncherLayout']();
}

export function GetLoadOrder() {
  return window['go']['main']['App']['GetLoadOrder']();
}

export function GetModsDir() {
  return window['go']['main']['App']['GetModsDir']();
}

export function GetModsDirStatus() {
  return window['go']['main']['App']['GetModsDirStatus']();
}

export function GetPlaysetNames() {
  return window['go']['main']['App']['GetPlaysetNames']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HasNewThumbnails() {
  return window['go']['main']['App']['HasNewThumbnails']();
}

export function IsUnsubscribeEnabled() {
  return window['go']['main']['App']['IsUnsubscribeEnabled']();
}

export function LaunchGame() {
  return window['go']['main']['App']['LaunchGame']();
}

export function OpenConfigFolder() {
  return window['go']['main']['App']['OpenConfigFolder']();
}

export function OpenExternalLink(arg1) {
  return window['go']['main']['App']['OpenExternalLink'](arg1);
}

export function OpenWorkshopItem(arg1) {
  return window['go']['main']['App']['OpenWorkshopItem'](arg1);
}

export function PickExecutable() {
  return window['go']['main']['App']['PickExecutable']();
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function RefreshWorkshopMetadataBatch(arg1) {
  return window['go']['main']['App']['RefreshWorkshopMetadataBatch'](arg1);
}

export function RefreshWorkshopMetadataForMod(arg1) {
  return window['go']['main']['App']['RefreshWorkshopMetadataForMod'](arg1);
}

export function RemoveConstraint(arg1, arg2) {
  return window['go']['main']['App']['RemoveConstraint'](arg1, arg2);
}

export function RemoveLoadFirst(arg1) {
  return window['go']['main']['App']['RemoveLoadFirst'](arg1);
}

export function RemoveLoadLast(arg1) {
  return window['go']['main']['App']['RemoveLoadLast'](arg1);
}

export function ResetGameExeToAuto() {
  return window['go']['main']['App']['ResetGameExeToAuto']();
}

export function ResetModsDirToAuto() {
  return window['go']['main']['App']['ResetModsDirToAuto']();
}

export function SaveCompiledLoadOrder() {
  return window['go']['main']['App']['SaveCompiledLoadOrder']();
}

export function SetActiveGame(arg1) {
  return window['go']['main']['App']['SetActiveGame'](arg1);
}

export function SetGameExe(arg1) {
  return window['go']['main']['App']['SetGameExe'](arg1);
}

export function SetLauncherActivePlaysetIndex(arg1) {
  return window['go']['main']['App']['SetLauncherActivePlaysetIndex'](arg1);
}

export function SetLauncherLayout(arg1) {
  return window['go']['main']['App']['SetLauncherLayout'](arg1);
}

export function SetLoadOrder(arg1) {
  return window['go']['main']['App']['SetLoadOrder'](arg1);
}

export function SetModsDir(arg1) {
  return window['go']['main']['App']['SetModsDir'](arg1);
}

export function UnsubscribeWorkshopMod(arg1) {
  return window['go']['main']['App']['UnsubscribeWorkshopMod'](arg1);
}
